[package]
name = "tuilade"
version = "0.1.0"
edition = "2021"
authors = ["Lux Amelia Phifollen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.93"
serde = "1.0.152"
serde_derive = "1.0.152"
